# Generated by Django 5.0 on 2024-01-23 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("youtube_auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="YoutubePlaylist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yt_playlist_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("image_url", models.URLField(blank=True, max_length=255, null=True)),
                (
                    "youtube_credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="youtube_auth.youtubecredential",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="YoutubeVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("artist", models.CharField(blank=True, max_length=255, null=True)),
                ("track", models.CharField(blank=True, max_length=255, null=True)),
                ("yid", models.CharField(max_length=255)),
                ("image_url", models.URLField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="youtube_vault.youtubeplaylist",
                    ),
                ),
                (
                    "youtube_credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="youtube_auth.youtubecredential",
                    ),
                ),
            ],
        ),
    ]
